language: ruby
rvm:
  - 1.9.2
  - 1.9.3
script: "rake spec"
before_install:
  - sudo apt-get install task
after_install:
  - cp -v /home/vagrant/builds/theunraveler/taskwarrior-web/spec/files/taskrc /home/vagrant/.taskrc
